name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry: ''
    - run: npm install
    - run: npm build
    - run: npm test
    - run: npm prepublish
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.SOMETHING2 }}